pipeline {
    agent any
    environment {
        IMAGE_NAME = "image-dfp-backend"
        NETWORK_NAME = 'dfp-backend-network'
        CONTAINER_NAME = 'container-dfp-backend'
        ENV_FILE = 'ENV_FILE'
    }

    stages {

        stage('Prepare Env File') {
            steps {
                withCredentials([file(credentialsId: env.ENV_FILE, variable: 'SECRET_FILE')]) {
                    dir('back-end') {
                        bat 'copy "%SECRET_FILE%" ".env"'
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                dir('back-end') {
                    bat 'npm install'
                }
            }
        }

        stage('Compile proyect') {
            steps {
                dir('back-end') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build image Docker') {
            steps {
                dir('back-end') {
                    bat 'docker build -t %IMAGE_NAME%:latest .'
                }
            }
        }

        stage('Check and create Red exists') {
            steps {
                bat '''
                for /f "tokens=*" %%i in ('docker network ls --format "{{.Name}}" ^| findstr /B /C:"%NETWORK_NAME%"') do (
                    set FOUND=1
                )
                if not defined FOUND (
                    docker network create %NETWORK_NAME%
                    echo Network %NETWORK_NAME% created.
                ) else (
                    echo Network %NETWORK_NAME% exists.
                )
                '''
            }
        }

        stage('Restart container proyect') {
            steps {
                script {
                    def isRunning = bat(
                        script: 'docker ps --format "{{.Names}}" | findstr /B /C:"%CONTAINER_NAME%"',
                        returnStatus: true
                    )

                    def exists = bat(
                        script: 'docker ps -a --format "{{.Names}}" | findstr /B /C:"%CONTAINER_NAME%"',
                        returnStatus: true
                    )

                    if (isRunning == 0) {
                        echo "Container '%CONTAINER_NAME%' is running. Stopping..."
                        bat 'docker stop %CONTAINER_NAME%'
                    }

                    if (exists == 0) {
                        echo "Container '%CONTAINER_NAME%' exists. Deleting..."
                        bat 'docker rm %CONTAINER_NAME%'
                    } else {
                        echo "Container '%CONTAINER_NAME%' does not exist. Will be created with docker-compose."
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                dir('back-end') {
                    bat 'docker-compose up -d'
                }
            }
        }
    }
}
